import { useEffect, useMemo, useState } from "react";
import { Check, ChevronLeft, MapPin, Search, ShoppingBag, X } from "lucide-react";
import { toast } from "sonner";
import { useServiceMenu } from "@/app/hooks/useServiceMenu";
import { projectId, publicAnonKey } from "@utils/supabase/info";
import { getStaffDisplayName, normalizeStaffList } from "@/app/lib/staffNickName";
import { resolveTierConfig } from "@/app/lib/booking-upsell/tier-config";
import { calculateAll, getUpsellContent } from "@/app/lib/booking-upsell/upsell-engine";
import type { AddonItem, CartLine, ServiceLine } from "@/app/lib/booking-upsell/types";
import type { Service } from "@/app/lib/admin-types";
import "./booking-v2.css";

type BookingStep = "menu" | "customize" | "schedule" | "details" | "review" | "confirmation";
type CustomerDetails = { name: string; phone: string; email: string; notes: string };
type StaffOption = { id: string; name: string; description: string };
type DisplayLine = ServiceLine & { category: string; groupName: string; image?: string; upsellable: boolean };

const categoryImages: Record<string, string> = {
  pedicure: "/cat-pedicure.jpg",
  manicure: "/cat-manicure.jpg",
  acrylic: "/cat-enhancements.jpg",
  waxing: "/cat-waxing.jpg",
  kids: "/cat-kids.jpg",
};

function money(value: number) { return `$${value}`; }
function dateLabel(value: string, compact = false) {
  const date = new Date(`${value}T12:00:00`);
  return new Intl.DateTimeFormat("en-US", compact ? { weekday: "short", month: "short", day: "numeric" } : { weekday: "short", month: "short", day: "numeric", year: "numeric" }).format(date);
}
async function fetchWithTimeout(input: RequestInfo | URL, init?: RequestInit, timeout = 10000) { const controller = new AbortController(); const timer = window.setTimeout(() => controller.abort(), timeout); try { return await fetch(input, { ...init, signal: controller.signal }); } finally { window.clearTimeout(timer); } }
function nextDates() {
  return Array.from({ length: 7 }, (_, index) => {
    const date = new Date();
    date.setHours(12, 0, 0, 0);
    date.setDate(date.getDate() + index);
    return { value: date.toISOString().slice(0, 10), weekday: new Intl.DateTimeFormat("en-US", { weekday: "short" }).format(date), day: date.getDate() };
  });
}

export function MenuStep({ lines, cartLines, query, onQuery, onSelect }: { lines: DisplayLine[]; cartLines: CartLine[]; query: string; onQuery: (value: string) => void; onSelect: (line: DisplayLine, foundationId: string) => void }) {
  const visible = lines.filter((line) => line.foundations.some((foundation) => `${foundation.name} ${line.category} ${line.groupName}`.toLowerCase().includes(query.toLowerCase())));
  const categories = [...new Map(visible.map((line) => [line.category, line])).entries()];
  return <>
    <header className="hero">
      <div className="hero-location"><MapPin className="hero-icon" /> Bitcoin Nail Bar - Westheimer</div>
      <h1>Book Your Visit</h1>
      <p>Nails, waxing and spa treatments. Add what you need - the price and how long you'll be with us update as you go.</p>
    </header>
    <div className="content-wrapper">
      <section className="step-header"><h2 className="step-title"><span className="step-badge">1</span> Choose your services</h2><div className="step-desc">Select your treatments to create your perfect visit.</div></section>
      <div className="svc-tools"><label className="svc-search"><Search className="hero-icon" /><input aria-label="Search services" type="search" value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search services - gel, wax, kids-" />{query && <button className="svc-clear" onClick={() => onQuery("")} aria-label="Clear search">-</button>}</label></div>
      <div className="svc-category-deck" aria-label="Featured Service Categories">{categories.slice(0, 5).map(([category, line]) => <a key={category} className="cat-card" href={`#category-${category}`}><div className="cat-card-img-wrap">{line.image && <img src={line.image} alt="" />}</div><div className="cat-card-body"><div className="cat-title">{category}</div><div className="cat-subtitle">Choose your ritual</div></div></a>)}</div>
      <div id="step-1-container">{visible.length === 0 ? <div className="section-box svc-empty">No services match -{query}-. Try a shorter search.</div> : visible.map((line) => {
        const selected = cartLines.find((cartLine) => cartLine.lineKey === line.key);
        return <section id={`category-${line.category}`} key={line.key} className="section-box"><div className="category-title">{line.category}</div><div className="category-desc">{line.groupName}</div><div className="foundation-grid">{line.foundations.map((foundation) => <button type="button" key={foundation.id} className={`foundation-card ${selected?.baseId === foundation.id ? "active" : ""}`} onClick={() => onSelect(line, foundation.id)}><span className="f-main"><span className="f-name">{foundation.name}</span><span className="f-meta">{foundation.time} min</span></span><span className="f-side"><span className="f-price">{money(foundation.price)}</span><span className="f-select" /></span></button>)}</div></section>;
      })}</div>
    </div>
  </>;
}

export function CustomizeSheet({ line, cartLine, addonsById, onBack, onDone, onRemove, onToggleAddon }: { line: DisplayLine; cartLine: CartLine; addonsById: Map<string, AddonItem>; onBack: () => void; onDone: () => void; onRemove: () => void; onToggleAddon: (id: string) => void }) {
  const base = line.foundations.find((foundation) => foundation.id === cartLine.baseId)!;
  const addons = line.addonGroups.flatMap((group) => group.items).map((addon) => addonsById.get(addon.id) || addon);
  return <div className="content-wrapper cw-no-hero"><section className="step-header step-2-box section-box"><div className="cz-bar"><button className="cz-back" onClick={onBack} aria-label="Back to services"><ChevronLeft /></button><div className="cz-bar-main"><div className="cz-eyebrow">{line.label}</div><h1 className="cz-title">{base.name}</h1></div><button className="cz-remove" onClick={onRemove}>Remove</button></div><div className="cz-recap"><div className="cz-recap-row"><span className="cz-recap-name">{base.name}</span><span className="cz-recap-meta">{money(base.price)} - {base.time} MIN</span></div></div><div className="step-desc">Add only what you love. Included treatments are clearly marked.</div><div className="addon-category"><div className="category-title">Enhance your ritual</div><div className="addon-grid">{addons.map((addon) => { const included = base.included.includes(addon.id); const selected = cartLine.addonIds.includes(addon.id); return <button type="button" key={addon.id} disabled={included} className={`addon-card ${included ? "included" : selected ? "selected" : ""}`} onClick={() => onToggleAddon(addon.id)}><span className="addon-info"><span className="addon-name">{addon.name}</span><span className="addon-desc">{addon.description || "Add a little more care"}</span></span><span className={included ? "addon-included-text" : "addon-price"}>{included ? "Included" : `+${money(addon.price)} - +${addon.time} min`}</span><span className="custom-radio" /></button>; })}</div></div><button className="cz-done" onClick={onDone}>Done - back to services</button></section></div>;
}

function CartItems({ calculation, onUpsell, cleared = false }: { calculation: ReturnType<typeof calculateAll>; onUpsell: (lineKey: string, foundationId: string) => void; cleared?: boolean }) {
  if (!calculation.servicesData.length) return <div className="bs-empty-state"><ShoppingBag className="bs-empty-icon" /><div className="bs-empty-title">Ready when you are</div><div className="bs-empty-desc">Your selections, estimated time, and total will appear here.</div>{cleared && <div className="bs-empty-desc">Cart cleared.</div>}</div>;
  return <>{calculation.servicesData.map(({ cartLine, item, addons, line, currentTotal }) => <div key={cartLine.lineKey} style={{ marginBottom: 24 }}><div className="cart-line-item base-item"><span className="li-main"><span>{item.name}</span><span className="li-time">{item.time} min</span></span><span className="li-price">{money(item.price)}</span></div>{addons.map((addon) => <div className="cart-line-item" key={addon.id}><span className="li-main"><span>+ {addon.name}</span><span className="li-time">+{addon.time} min</span></span><span className="li-price">+{money(addon.price)}</span></div>)}{calculation.upsells[line.key]?.target && (() => { const result = calculation.upsells[line.key]; const content = getUpsellContent(result.target!, item.name, currentTotal); return <div className="upsell-box"><div className="upsell-label">{content.label}</div><div className="upsell-desc">{content.description}</div><button className="btn-upgrade" onClick={() => onUpsell(line.key, result.target!.id)}>{content.buttonText}</button></div>; })()}</div>)}</>;
}

export function CartRail({ calculation, step, onContinue, onUpsell, cleared }: { calculation: ReturnType<typeof calculateAll>; step: BookingStep; onContinue: () => void; onUpsell: (lineKey: string, id: string) => void; cleared: boolean }) {
  const label = step === "schedule" ? "CONTINUE TO DETAILS" : step === "details" ? "REVIEW BOOKING" : step === "review" ? `CONFIRM APPOINTMENT - ${money(calculation.grandTotal)}` : step === "confirmation" ? "APPOINTMENT CONFIRMED" : `CONTINUE TO BOOK - ${money(calculation.grandTotal)}`;
  return <aside className="sidebar"><div className="cart-content"><div className="cart-header">YOUR SELECTIONS</div><h2 className="cart-title">Your Selections</h2><CartItems calculation={calculation} onUpsell={onUpsell} cleared={cleared} /></div><div className="cart-footer"><div className="cart-time"><span>{calculation.grandTime} min</span><span>Estimated service time</span></div><div className="cart-total-row"><span>Total</span><span className="total-price">{money(calculation.grandTotal)}</span></div><button className="btn-book" disabled={!calculation.servicesData.length || step === "confirmation"} onClick={onContinue}>{label}</button><div className="deposit-note">No deposit required - We'll confirm your time by text</div></div></aside>;
}

export function MobileCartBar({ calculation, onOpen, onContinue, cleared }: { calculation: ReturnType<typeof calculateAll>; onOpen: () => void; onContinue: () => void; cleared: boolean }) { return <div className="mobile-cart-bar"><button className="mcb-main" onClick={onOpen}><span className="mcb-info"><span className="mcb-count">{cleared ? "Cart cleared - 0 min" : `${calculation.servicesData.length} item${calculation.servicesData.length === 1 ? "" : "s"} - ${calculation.grandTime} min`}</span><span className="mcb-total">{money(calculation.grandTotal)}</span></span><span className="mcb-book" onClick={(event) => { event.stopPropagation(); onContinue(); }}>Continue {"<"}</span></button></div>; }
export function BottomSheet({ open, calculation, onClose, onContinue, onUpsell, cleared }: { open: boolean; calculation: ReturnType<typeof calculateAll>; onClose: () => void; onContinue: () => void; onUpsell: (lineKey: string, id: string) => void; cleared: boolean }) { return <div className={`bottom-sheet-overlay ${open ? "open" : ""}`} onClick={onClose}><div className="bottom-sheet" onClick={(event) => event.stopPropagation()}><div className="bs-handle" /><div className="bs-header"><h3>Your Selections</h3><button className="bs-close" onClick={onClose}><X /></button></div><div className="bs-body"><CartItems calculation={calculation} onUpsell={onUpsell} cleared={cleared} /></div><div className="bs-footer"><div className="bs-total-row"><span>Total - {calculation.grandTime} min</span><span className="bs-total-price">{money(calculation.grandTotal)}</span></div><button className="bs-btn-book" disabled={!calculation.servicesData.length} onClick={onContinue}>CONTINUE TO BOOK - {money(calculation.grandTotal)}</button></div></div></div>; }

export function ScheduleStep({ selectedDate, selectedTime, selectedStaff, slots, loading, staff, onDate, onTime, onStaff, onBack, onNext }: { selectedDate: string; selectedTime: string; selectedStaff: string | null; slots: string[]; loading: boolean; staff: StaffOption[]; onDate: (value: string) => void; onTime: (value: string) => void; onStaff: (value: string) => void; onBack: () => void; onNext: () => void }) { const canContinue = Boolean(selectedDate && selectedTime && selectedStaff !== null); return <StepCanvas title="Choose date, time & specialist"><div className="bk-section"><div className="bk-section-title">1. Select Date</div><div className="date-picker">{nextDates().map((date) => <button key={date.value} className={`date-option ${selectedDate === date.value ? "selected" : ""}`} onClick={() => onDate(date.value)}><span className="date-option-day">{date.weekday}</span><span className="date-option-num">{date.day}</span></button>)}</div></div>{selectedDate && <div className="bk-section"><div className="bk-section-title">2. Select Time</div>{loading ? <p>Finding available slots-</p> : <div className="time-picker">{slots.map((slot) => <button key={slot} className={`time-option ${selectedTime === slot ? "selected" : ""}`} onClick={() => onTime(slot)}>{slot}</button>)}</div>}{!loading && !slots.length && <p>No online availability is currently available for this day.</p>}</div>}{selectedTime && <div className="bk-section"><div className="bk-section-title">3. Select Specialist</div><div className="staff-picker"><button className={`staff-option ${selectedStaff === "" ? "selected" : ""}`} onClick={() => onStaff("")}><span className="staff-avatar">ANY</span><span className="staff-info"><span className="staff-name">Any available specialist</span><span className="staff-desc">Flexible / earliest available</span></span></button>{staff.map((member) => <button key={member.id} className={`staff-option ${selectedStaff === member.id ? "selected" : ""}`} onClick={() => onStaff(member.id)}><span className="staff-avatar">{member.name.slice(0, 1)}</span><span className="staff-info"><span className="staff-name">{member.name}</span><span className="staff-desc">{member.description}</span></span></button>)}</div></div>}<button className="bk-nav-btn bk-btn-primary" disabled={!canContinue} onClick={onNext}>Continue to details</button><button className="bk-nav-btn bk-btn-secondary" onClick={onBack}>{"< Back to services"}</button></StepCanvas>; }

export function DetailsStep({ details, onChange, onBack, onNext }: { details: CustomerDetails; onChange: (next: CustomerDetails) => void; onBack: () => void; onNext: () => void }) { const update = (key: keyof CustomerDetails, value: string) => onChange({ ...details, [key]: value }); return <StepCanvas title="Your Contact Details"><p>We'll text your appointment confirmation and reminder to this number.</p><div className="bk-section"><div className="bk-field"><label className="bk-label">Full Name *</label><input className="bk-input" value={details.name} onChange={(event) => update("name", event.target.value)} autoComplete="name" /></div><div className="bk-field"><label className="bk-label">Phone Number *</label><input className="bk-input" value={details.phone} onChange={(event) => update("phone", event.target.value)} autoComplete="tel" /></div><div className="bk-field"><label className="bk-label">Email Address (Optional)</label><input className="bk-input" type="email" value={details.email} onChange={(event) => update("email", event.target.value)} autoComplete="email" /></div><div className="bk-field"><label className="bk-label">Special Requests / Notes (Optional)</label><textarea className="bk-input" value={details.notes} onChange={(event) => update("notes", event.target.value)} /></div></div><button className="bk-nav-btn bk-btn-primary" onClick={onNext}>Review booking</button><button className="bk-nav-btn bk-btn-secondary" onClick={onBack}>{"< Back to schedule"}</button></StepCanvas>; }

export function ReviewStep({ calculation, date, time, staff, details, onSchedule, onDetails, onBack, onConfirm, submitting }: { calculation: ReturnType<typeof calculateAll>; date: string; time: string; staff: string; details: CustomerDetails; onSchedule: () => void; onDetails: () => void; onBack: () => void; onConfirm: () => void; submitting: boolean }) { return <StepCanvas title="Review your appointment"><div className="bk-review-canvas"><div className="bk-review-section"><div className="bk-review-eyebrow">Services</div>{calculation.servicesData.map(({ item, addons }) => <div key={item.id}><div className="bk-review-service-item"><span className="bk-review-svc-main"><span className="bk-review-svc-name">{item.name}</span><span className="bk-review-svc-time">{item.time} min</span></span><span className="bk-review-svc-price">{money(item.price)}</span></div>{addons.map((addon) => <div key={addon.id} className="bk-review-addon-item"><span>+ {addon.name} +{addon.time} min</span><span>+{money(addon.price)}</span></div>)}</div>)}</div><div className="bk-review-divider" /><div className="bk-review-section"><div className="bk-review-row-header"><span className="bk-review-eyebrow">Schedule</span><button className="bk-review-edit-btn" onClick={onSchedule}>Edit</button></div><div className="bk-review-value-primary">{dateLabel(date)} - {time}</div><div className="bk-review-value-secondary">with {staff || "Any available specialist"}</div></div><div className="bk-review-divider" /><div className="bk-review-section"><div className="bk-review-row-header"><span className="bk-review-eyebrow">Client Details</span><button className="bk-review-edit-btn" onClick={onDetails}>Edit</button></div><div className="bk-review-value-primary">{details.name} - {details.phone}</div>{details.email && <div className="bk-review-value-secondary">{details.email}</div>}</div><div className="bk-review-divider" /><div className="bk-review-total-row"><span className="bk-review-total-label">Total - {calculation.grandTime} min</span><span className="bk-review-total-price">{money(calculation.grandTotal)}</span></div></div><button className="bk-nav-btn bk-btn-primary" disabled={submitting} onClick={onConfirm}>{submitting ? "CONFIRMING-" : `CONFIRM APPOINTMENT - ${money(calculation.grandTotal)}`}</button><button className="bk-nav-btn bk-btn-secondary" onClick={onBack}>{"< Back to details"}</button></StepCanvas>; }

export function ConfirmationStep({ calculation, date, time, staff, details, onRestart }: { calculation: ReturnType<typeof calculateAll>; date: string; time: string; staff: string; details: CustomerDetails; onRestart: () => void }) { return <StepCanvas title=""><div className="bk-review-canvas"><Check size={42} color="#298F65" /><div className="bk-review-eyebrow">Booking confirmed</div><h1 className="cz-title" style={{ color: "white" }}>Booking Confirmed!</h1><p className="bk-review-value-secondary">We've sent an appointment confirmation text to {details.phone}.</p><div className="bk-review-divider" /><div className="bk-review-value-primary">{dateLabel(date)} at {time}</div><div className="bk-review-value-secondary">with {staff || "Any available specialist"}</div><div className="bk-review-divider" />{calculation.servicesData.map(({ item }) => <div className="bk-review-service-item" key={item.id}><span>{item.name}</span><span>{money(item.price)}</span></div>)}<div className="bk-review-total-row"><span>Total - {calculation.grandTime} min</span><span className="bk-review-total-price">{money(calculation.grandTotal)}</span></div></div><button className="bk-nav-btn bk-btn-secondary" onClick={onRestart}>Book another appointment</button></StepCanvas>; }
function StepCanvas({ title, children }: { title: string; children: React.ReactNode }) { return <div className="content-wrapper cw-no-hero"><section className="section-box" style={{ padding: "24px 20px" }}>{title && <h1 className="cz-title">{title}</h1>}{children}</section></div>; }

export default function BookingV2Page() {
  const { services, loading } = useServiceMenu();
  const [step, setStep] = useState<BookingStep>("menu"); const [cartLines, setCartLines] = useState<CartLine[]>([]); const [cartCleared, setCartCleared] = useState(false); const [branches, setBranches] = useState<Array<{ id: string }>>([]); const [query, setQuery] = useState(""); const [customizing, setCustomizing] = useState<string | null>(null); const [sheetOpen, setSheetOpen] = useState(false); const [date, setDate] = useState(""); const [time, setTime] = useState(""); const [staffId, setStaffId] = useState<string | null>(null); const [staff, setStaff] = useState<StaffOption[]>([]); const [slots, setSlots] = useState<string[]>([]); const [checking, setChecking] = useState(false); const [details, setDetails] = useState<CustomerDetails>({ name: "", phone: "", email: "", notes: "" }); const [submitting, setSubmitting] = useState(false);
  const { lines: tierLines, configuredAddons } = useMemo(() => resolveTierConfig(services), [services]);
  const displayLines = useMemo<DisplayLine[]>(() => { const tierIds = new Set(tierLines.flatMap((line) => line.foundations.map((foundation) => foundation.id))); const addonIds = new Set(configuredAddons.map((addon) => addon.id)); const tierDisplay = tierLines.map((line) => ({ ...line, category: "Pedicure", groupName: "Signature Pedicure Rituals", image: categoryImages.pedicure, upsellable: true })); const singles = services.filter((service) => !tierIds.has(service.id) && !addonIds.has(service.id) && service.status !== "disabled" && service.price > 0).map((service) => ({ key: `service-${service.id}`, label: service.category || service.categoryKey || "Services", category: service.category || service.categoryKey || "Services", groupName: service.groupName || "Services", image: categoryImages[service.categoryKey || ""], upsellable: false, foundations: [{ id: service.id, name: service.name, price: service.price, time: service.durationMinutes || 45, included: [], source: { categoryKey: service.categoryKey || "", groupName: service.groupName || "", name: service.name } }], addonGroups: [] })); return [...tierDisplay, ...singles]; }, [configuredAddons, services, tierLines]);
  const addonMap = useMemo(() => new Map(configuredAddons.map((addon) => [addon.id, addon])), [configuredAddons]); const calculation = useMemo(() => calculateAll(cartLines, displayLines, addonMap), [addonMap, cartLines, displayLines]);
  useEffect(() => { fetch(`https://${projectId}.supabase.co/functions/v1/make-server-84f9c112/branches`, { headers: { Authorization: `Bearer ${publicAnonKey}` } }).then((response) => response.json()).then((data) => { if (data.success && Array.isArray(data.data)) setBranches(data.data); }).catch(() => toast.error("Could not load locations")); }, []);
  useEffect(() => { fetch(`https://${projectId}.supabase.co/functions/v1/make-server-84f9c112/staff`, { headers: { Authorization: `Bearer ${publicAnonKey}` } }).then((response) => response.json()).then((data) => { if (data.success && Array.isArray(data.data)) setStaff(normalizeStaffList(data.data).filter((member: any) => member.isActive !== false).map((member: any) => ({ id: member.id, name: getStaffDisplayName(member), description: member.role || "Nail specialist" }))); }).catch(() => toast.error("Could not load specialists")); }, []);
  useEffect(() => { if (!date || !cartLines.length) return; setChecking(true); setSlots([]); fetch(`https://${projectId}.supabase.co/functions/v1/make-server-84f9c112/appointments/availability`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${publicAnonKey}` }, body: JSON.stringify({ date, staffId: staffId || undefined, serviceIds: cartLines.flatMap((cartLine) => [cartLine.baseId, ...cartLine.addonIds]) }) }).then((response) => response.json()).then((data) => { if (data.success && Array.isArray(data.data)) setSlots(data.data); else toast.error("Could not load available times"); }).catch(() => toast.error("Connection error while checking availability")).finally(() => setChecking(false)); }, [cartLines, date, staffId]);
  const select = (line: DisplayLine, baseId: string) => { setCartCleared(false); setCartLines((current) => { const existing = current.find((cartLine) => cartLine.lineKey === line.key); const base = line.foundations.find((foundation) => foundation.id === baseId)!; if (!existing) return [...current, { lineKey: line.key, baseId, addonIds: [] }]; return current.map((cartLine) => cartLine.lineKey === line.key ? { ...cartLine, baseId, addonIds: cartLine.addonIds.filter((id) => !base.included.includes(id)) } : cartLine); }); setCustomizing(line.key); setStep("customize"); };
  const upgrade = (lineKey: string, baseId: string) => { const line = displayLines.find((item) => item.key === lineKey)!; select(line, baseId); setSheetOpen(false); };
  const continueBooking = () => { setSheetOpen(false); if (!cartLines.length) return; if (step === "menu" || step === "customize") setStep("schedule"); else if (step === "schedule" && date && time && staffId !== null) setStep("details"); else if (step === "details") { if (!details.name.trim() || details.phone.replace(/\D/g, "").length < 7) { toast.error("Please enter your name and a valid phone number"); return; } setStep("review"); } else if (step === "review") submit(); };
  const submit = async () => { setSubmitting(true); try { const appointmentTime = new Date(`${date}T${to24Hour(time)}`).toISOString(); const selectedStaff = staffId || staff[0]?.id; const appointmentId = `appointment:${Date.now()}`; await fetchWithTimeout(`https://${projectId}.supabase.co/functions/v1/make-server-84f9c112/customers/book`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${publicAnonKey}` }, body: JSON.stringify({ phone: details.phone, full_name: details.name, email: details.email.trim() || null, appointment_id: appointmentId, appointment_time: appointmentTime, appointment_amount: calculation.grandTotal }) }); const response = await fetch(`https://${projectId}.supabase.co/functions/v1/make-server-84f9c112/appointments`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${publicAnonKey}` }, body: JSON.stringify({ customerName: details.name, customerPhone: details.phone, customerEmail: details.email.trim() || null, branchId: branches[0]?.id, staffId: selectedStaff, serviceIds: cartLines.flatMap((cartLine) => [cartLine.baseId, ...cartLine.addonIds]), serviceNames: calculation.servicesData.map(({ item }) => item.name).join(", "), appointmentTime, notes: details.notes }) }); const data = await response.json(); if (!data.success) throw new Error(data.error || "Could not create appointment"); await fetch(`https://${projectId}.supabase.co/functions/v1/make-server-84f9c112/customers`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${publicAnonKey}` }, body: JSON.stringify({ phone: details.phone.replace(/\\D/g, ""), name: details.name, email: details.email.trim() || null }) }); setStep("confirmation"); } catch (error: any) { toast.error(error.message || "Could not confirm appointment"); } finally { setSubmitting(false); } };
  const restart = () => { setStep("menu"); setCartLines([]); setCartCleared(false); setDate(""); setTime(""); setStaffId(null); setDetails({ name: "", phone: "", email: "", notes: "" }); };
  const selectedLine = displayLines.find((line) => line.key === customizing); const selectedCartLine = cartLines.find((line) => line.lineKey === customizing);
  return <main className="booking-v2">{loading ? <div className="content-wrapper"><p>Loading services-</p></div> : <div className="layout"><div className="main-content">{step === "menu" && <MenuStep lines={displayLines} cartLines={cartLines} query={query} onQuery={setQuery} onSelect={select} />}{step === "customize" && selectedLine && selectedCartLine && <CustomizeSheet line={selectedLine} cartLine={selectedCartLine} addonsById={addonMap} onBack={() => setStep("menu")} onDone={() => setStep("menu")} onRemove={() => { setCartLines((current) => current.filter((line) => line.lineKey !== selectedLine.key)); setCartCleared(true); setStep("menu"); }} onToggleAddon={(id) => setCartLines((current) => current.map((line) => line.lineKey === selectedLine.key ? { ...line, addonIds: line.addonIds.includes(id) ? line.addonIds.filter((item) => item !== id) : [...line.addonIds, id] } : line))} />}{step === "schedule" && <ScheduleStep selectedDate={date} selectedTime={time} selectedStaff={staffId} slots={slots} loading={checking} staff={staff} onDate={(value) => { setDate(value); setTime(""); setStaffId(null); }} onTime={(value) => { setTime(value); setStaffId(null); }} onStaff={setStaffId} onBack={() => setStep("menu")} onNext={continueBooking} />}{step === "details" && <DetailsStep details={details} onChange={setDetails} onBack={() => setStep("schedule")} onNext={continueBooking} />}{step === "review" && <ReviewStep calculation={calculation} date={date} time={time} staff={staff.find((member) => member.id === staffId)?.name || ""} details={details} onSchedule={() => setStep("schedule")} onDetails={() => setStep("details")} onBack={() => setStep("details")} onConfirm={continueBooking} submitting={submitting} />}{step === "confirmation" && <ConfirmationStep calculation={calculation} date={date} time={time} staff={staff.find((member) => member.id === staffId)?.name || ""} details={details} onRestart={restart} />}</div><CartRail calculation={calculation} step={step} onContinue={continueBooking} onUpsell={upgrade} cleared={cartCleared} /><MobileCartBar calculation={calculation} onOpen={() => setSheetOpen(true)} onContinue={continueBooking} cleared={cartCleared} /><BottomSheet open={sheetOpen} calculation={calculation} onClose={() => setSheetOpen(false)} onContinue={continueBooking} onUpsell={upgrade} cleared={cartCleared} /></div>}</main>;
}

function to24Hour(value: string) { const match = value.match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i); if (!match) return "09:00:00"; const [, hourValue, minutes, period] = match; let hour = Number(hourValue); if (period.toUpperCase() === "PM" && hour !== 12) hour += 12; if (period.toUpperCase() === "AM" && hour === 12) hour = 0; return `${String(hour).padStart(2, "0")}:${minutes}:00`; }