/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pwmrmcipniefewufwjjy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3bXJtY2lwbmllZmV3dWZ3amp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1NTgwMDEsImV4cCI6MjA4MjEzNDAwMX0.i8S8gaa2t3NNKq-BUz-600eRYa8tfJeW14Ydold-i9k"